version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: feedme-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: feedme
      POSTGRES_PASSWORD: feedme_password
      POSTGRES_DB: feedme
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U feedme"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Uncomment to add pgAdmin for database management
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: feedme-pgadmin
  #   restart: unless-stopped
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: admin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin_password
  #   ports:
  #     - "5050:80"
  #   depends_on:
  #     - postgres

  # Backend and frontend services will be added later
  # They will be built from Dockerfiles in the respective directories

volumes:
  postgres_data: